/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
//   // But you can create a sidebar manually
//   // tutorialSidebar: [
//   //   {
//   //     type: "category",
//   //     label: "Tutorial",
//   //     items: ["hello"],
//   //   },
//   // ],
// };

// module.exports = sidebars;

module.exports = {
  docs: [
    {
      type: "category",
      label: "장영실의 발명품",
      items: [
        "장영실의 발명품/간의",
        "장영실의 발명품/혼천의",
        "장영실의 발명품/자격루",
        "장영실의 발명품/갑인자",
        "장영실의 발명품/앙부일구",
        "장영실의 발명품/규표",
        "장영실의 발명품/일성정시의",
        "장영실의 발명품/옥루",
        "장영실의 발명품/수표",
        "장영실의 발명품/측우기",
      ],
    },
    {
      type: "category",
      label: "장영실의 스토리",
      items: ["장영실의 스토리/가마썰"],
    },
  ],
};
